const EXAMPLE_CSV=`Criterio;Pregunta;Aspecto evaluado;Nivel insuficiente (0%);Puntos 0%;Nivel básico (25%);Puntos 25%;Nivel adecuado (50%);Puntos 50%;Nivel notable (75%);Puntos 75%;Nivel excelente (100%);Puntos 100%;Máximo;Puntuación obtenida
CE1.1;P1. Definición del problema;Define el problema tecnológico y lo diferencia de una posible solución.;No identifica el problema o propone directamente una solución.;0;Identifica parcialmente el problema, pero lo formula de forma incompleta o confunde problema y solución.;0,5;Define correctamente el problema, aunque con alguna imprecisión.;1;Define claramente el problema y lo diferencia de la solución.;1,5;Define con precisión el problema, necesidad u oportunidad y lo diferencia claramente de posibles soluciones.;2;2;
CE1.1;P2. Requisitos y restricciones;Identifica requisitos y restricciones del sistema.;No identifica requisitos ni restricciones válidos.;0;Identifica solo uno o dos elementos, con confusiones importantes.;0,5;Identifica varios requisitos y restricciones, aunque falta algún elemento o hay alguna imprecisión.;1;Identifica correctamente los requisitos y restricciones principales.;1,5;Identifica y distingue correctamente los requisitos y restricciones relevantes, relacionándolos con el caso.;2;2;`;

const state={rubric:[],selections:new Map()};const $=s=>document.querySelector(s);
function norm(v){return String(v??"").replace(/\r/g,"").trim()}
function num(v){const n=Number(norm(v).replace(/\./g,"").replace(",", "."));return Number.isFinite(n)?n:0}
function csvLine(line,d){const a=[];let c="",q=false;for(let i=0;i<line.length;i++){const x=line[i],n=line[i+1];if(x==='"'){if(q&&n==='"'){c+='"';i++}else q=!q}else if(x===d&&!q){a.push(c);c=""}else c+=x}a.push(c);return a}
function parseCsv(text){const lines=norm(text).split("\n").filter(x=>x.trim());if(lines.length<2)throw Error("El CSV no contiene suficientes filas.");const d=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?";":",";const hs=csvLine(lines[0],d).map(norm),idx={};hs.forEach((h,i)=>idx[h]=i);for(const h of["Criterio","Pregunta","Aspecto evaluado"])if(idx[h]===undefined)throw Error("Falta la columna obligatoria: "+h);const defs=[["0","Insuficiente",0,"Nivel insuficiente (0%)","Puntos 0%"],["25","Básico",25,"Nivel básico (25%)","Puntos 25%"],["50","Adecuado",50,"Nivel adecuado (50%)","Puntos 50%"],["75","Notable",75,"Nivel notable (75%)","Puntos 75%"],["100","Excelente",100,"Nivel excelente (100%)","Puntos 100%"]];return lines.slice(1).map((line,i)=>{const r=csvLine(line,d);const levels=defs.map(([key,label,pct,lh,ph])=>({key,label,pct,description:norm(r[idx[lh]]),points:num(r[idx[ph]])}));return{id:"q"+i,criterion:norm(r[idx["Criterio"]]),question:norm(r[idx["Pregunta"]]),aspect:norm(r[idx["Aspecto evaluado"]]),levels,max:idx["Máximo"]!==undefined?num(r[idx["Máximo"]]):Math.max(...levels.map(x=>x.points))}})}
function groups(items){const m=new Map();items.forEach(x=>{if(!m.has(x.criterion))m.set(x.criterion,[]);m.get(x.criterion).push(x)});return m}
function fmt(v){return new Intl.NumberFormat("es-ES",{maximumFractionDigits:2}).format(v)}
function esc(t){return String(t??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function updateScore(){const max=state.rubric.reduce((s,x)=>s+x.max,0),got=state.rubric.reduce((s,x)=>s+(state.selections.get(x.id)?.points||0),0),ev=state.rubric.filter(x=>state.selections.has(x.id)).length,total=state.rubric.length,p=max?(got/max)*100:0,pp=total?(ev/total)*100:0;$("#scoreObtained").textContent=fmt(got);$("#scoreMax").textContent=fmt(max);$("#scorePercent").textContent=fmt(p);$("#progressText").textContent=ev+" / "+total+" preguntas evaluadas";$("#progressPercent").textContent=Math.round(pp)+"%";$("#progressFill").style.width=pp+"%";const s=$("#criterionSummary");s.innerHTML="";groups(state.rubric).forEach((items,c)=>{const mx=items.reduce((a,x)=>a+x.max,0),ob=items.reduce((a,x)=>a+(state.selections.get(x.id)?.points||0),0),pill=document.createElement("div");pill.className="criterion-pill";pill.innerHTML=esc(c)+" <strong>"+fmt(mx?(ob/mx)*100:0)+"%</strong>";s.appendChild(pill)})}
function render(){const box=$("#rubricContainer");box.innerHTML="";groups(state.rubric).forEach((items,c)=>{const sec=document.createElement("section");sec.className="criterion-block";const mx=items.reduce((s,x)=>s+x.max,0),ev=items.filter(x=>state.selections.has(x.id)).length,ob=items.reduce((s,x)=>s+(state.selections.get(x.id)?.points||0),0);const head=document.createElement("div");head.className="criterion-head";head.innerHTML='<h2 class="criterion-title">'+esc(c)+'</h2><div class="criterion-meta">'+ev+" / "+items.length+" preguntas evaluadas · "+fmt(ob)+" / "+fmt(mx)+" puntos</div>";sec.appendChild(head);items.forEach(item=>{const card=document.createElement("article");card.className="question-card";const sel=state.selections.get(item.id);const buttons=item.levels.map(l=>'<button class="level-btn '+(sel?.key===l.key?"selected":"")+'" data-q="'+item.id+'" data-level="'+l.key+'"><span class="level-name">'+l.label+" · "+l.pct+'%</span><span class="level-points">'+fmt(l.points)+' pt</span><span class="level-desc">'+esc(l.description)+"</span></button>").join("");card.innerHTML='<div class="question-top"><div><h3 class="question-title">'+esc(item.question)+'</h3><p class="question-aspect">'+esc(item.aspect)+'</p></div><div class="question-score">'+(sel?fmt(sel.points):"—")+" / "+fmt(item.max)+'</div></div><div class="level-grid">'+buttons+"</div>";card.querySelectorAll(".level-btn").forEach(b=>b.addEventListener("click",()=>{state.selections.set(item.id,item.levels.find(l=>l.key===b.dataset.level));save();render()}));sec.appendChild(card)});box.appendChild(sec)});updateScore()}
function save(){localStorage.setItem("rubricas-app-state",JSON.stringify({csv:$("#csvInput").value,rubric:state.rubric,selections:[...state.selections],student:{name:$("#studentName").value,group:$("#groupName").value,activity:$("#activityName").value}}))}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}
function load(){try{const r=parseCsv($("#csvInput").value);state.rubric=r;state.selections.clear();$("#importView").classList.add("hidden");$("#rubricView").classList.remove("hidden");render();save();toast("Rúbrica cargada: "+r.length+" preguntas");window.scrollTo({top:0,behavior:"smooth"})}catch(e){toast(e.message||"No se ha podido leer el CSV.")}}
$("#loadBtn").addEventListener("click",load);$("#exampleBtn").addEventListener("click",()=>{$("#csvInput").value=EXAMPLE_CSV;$("#parseStatus").textContent="Ejemplo cargado."});$("#resetBtn").addEventListener("click",()=>{localStorage.removeItem("rubricas-app-state");state.rubric=[];state.selections.clear();$("#rubricView").classList.add("hidden");$("#importView").classList.remove("hidden");$("#csvInput").value="";$("#parseStatus").textContent="Esperando CSV…";window.scrollTo({top:0,behavior:"smooth"})});$("#printBtn").addEventListener("click",()=>window.print());["studentName","groupName","activityName"].forEach(id=>$("#"+id).addEventListener("input",save));$("#csvInput").addEventListener("input",()=>{try{$("#parseStatus").textContent="CSV válido · "+parseCsv($("#csvInput").value).length+" preguntas detectadas"}catch{if($("#csvInput").value.trim())$("#parseStatus").textContent="Revisa el formato del CSV.";else $("#parseStatus").textContent="Esperando CSV…"}});
(()=>{const raw=localStorage.getItem("rubricas-app-state");if(!raw)return;try{const d=JSON.parse(raw);if(d.csv)$("#csvInput").value=d.csv;if(d.rubric?.length){state.rubric=d.rubric;state.selections=new Map(d.selections||[]);$("#studentName").value=d.student?.name||"";$("#groupName").value=d.student?.group||"";$("#activityName").value=d.student?.activity||"";$("#importView").classList.add("hidden");$("#rubricView").classList.remove("hidden");render()}}catch{}})();