const EXAMPLE_CSV=`Criterio;Pregunta;Aspecto evaluado;Nivel insuficiente (0%);Puntos 0%;Nivel básico (25%);Puntos 25%;Nivel adecuado (50%);Puntos 50%;Nivel notable (75%);Puntos 75%;Nivel excelente (100%);Puntos 100%;Máximo;Puntuación obtenida
CE1.1;P1. Definición del problema;Define el problema tecnológico y lo diferencia de una posible solución.;No identifica el problema o propone directamente una solución.;0;Identifica parcialmente el problema, pero lo formula de forma incompleta o confunde problema y solución.;0,5;Define correctamente el problema, aunque con alguna imprecisión.;1;Define claramente el problema y lo diferencia de la solución.;1,5;Define con precisión el problema, necesidad u oportunidad y lo diferencia claramente de posibles soluciones.;2;2;
CE1.1;P2. Requisitos y restricciones;Identifica requisitos y restricciones del sistema.;No identifica requisitos ni restricciones válidos.;0;Identifica solo uno o dos elementos, con confusiones importantes.;0,5;Identifica varios requisitos y restricciones, aunque falta algún elemento o hay alguna imprecisión.;1;Identifica correctamente los requisitos y restricciones principales.;1,5;Identifica y distingue correctamente los requisitos y restricciones relevantes, relacionándolos con el caso.;2;2;`;

const $=s=>document.querySelector(s);
const state={rubric:[],students:[],activeStudentId:null,session:{group:"",activity:""},view:"full",quickIndex:0};

function norm(v){return String(v??"").replace(/\r/g,"").trim()}
function num(v){const n=Number(norm(v).replace(/\./g,"").replace(",", "."));return Number.isFinite(n)?n:0}
function csvLine(line,d){const a=[];let c="",q=false;for(let i=0;i<line.length;i++){const x=line[i],n=line[i+1];if(x==='"'){if(q&&n==='"'){c+='"';i++}else q=!q}else if(x===d&&!q){a.push(c);c=""}else c+=x}a.push(c);return a}
function parseCsv(text){const lines=norm(text).split("\n").filter(x=>x.trim());if(lines.length<2)throw Error("El CSV no contiene suficientes filas.");const d=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?";":",";const hs=csvLine(lines[0],d).map(norm),idx={};hs.forEach((h,i)=>idx[h]=i);for(const h of["Criterio","Pregunta","Aspecto evaluado"])if(idx[h]===undefined)throw Error("Falta la columna obligatoria: "+h);const defs=[["0","Insuficiente",0,"Nivel insuficiente (0%)","Puntos 0%"],["25","Básico",25,"Nivel básico (25%)","Puntos 25%"],["50","Adecuado",50,"Nivel adecuado (50%)","Puntos 50%"],["75","Notable",75,"Nivel notable (75%)","Puntos 75%"],["100","Excelente",100,"Nivel excelente (100%)","Puntos 100%"]];return lines.slice(1).map((line,i)=>{const r=csvLine(line,d);const levels=defs.map(([key,label,pct,lh,ph])=>({key,label,pct,description:norm(r[idx[lh]]),points:num(r[idx[ph]])}));return{id:"q"+i,criterion:norm(r[idx["Criterio"]]),question:norm(r[idx["Pregunta"]]),aspect:norm(r[idx["Aspecto evaluado"]]),levels,max:idx["Máximo"]!==undefined?num(r[idx["Máximo"]]):Math.max(...levels.map(x=>x.points))}})}
function groups(items){const m=new Map();items.forEach(x=>{if(!m.has(x.criterion))m.set(x.criterion,[]);m.get(x.criterion).push(x)});return m}
function fmt(v){return new Intl.NumberFormat("es-ES",{maximumFractionDigits:2}).format(v)}
function esc(t){return String(t??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function uid(){return "s"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function current(){return state.students.find(s=>s.id===state.activeStudentId)||null}
function getSelectionMap(student){return new Map(student?.selections||[])}
function totals(student){const sel=getSelectionMap(student),max=state.rubric.reduce((s,x)=>s+x.max,0),got=state.rubric.reduce((s,x)=>s+(sel.get(x.id)?.points||0),0),ev=state.rubric.filter(x=>sel.has(x.id)).length;return{max,got,ev,total:state.rubric.length,pct:max?got/max*100:0,progress:state.rubric.length?ev/state.rubric.length*100:0}}
function save(){localStorage.setItem("rubricas-app-v2",JSON.stringify({csv:$("#csvInput")?.value||"",rubric:state.rubric,students:state.students,activeStudentId:state.activeStudentId,session:state.session}))}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$("#"+id).classList.remove("hidden");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===id))}
function ensureStudent(){if(state.activeStudentId)return current();if(!state.students.length){addStudent("Alumno/a 1")}state.activeStudentId=state.students[0].id;return current()}
function addStudent(name){name=norm(name);if(!name)return;const s={id:uid(),name,selections:[]};state.students.push(s);state.activeStudentId=s.id;save();renderStudents();renderRubric();toast("Alumno añadido")}
function deleteStudent(id){const s=state.students.find(x=>x.id===id);if(!s)return;if(!confirm("¿Eliminar a "+s.name+" y su evaluación?"))return;state.students=state.students.filter(x=>x.id!==id);if(state.activeStudentId===id)state.activeStudentId=state.students[0]?.id||null;save();renderStudents();if(state.activeStudentId)renderRubric()}
function renderStudents(){const grid=$("#studentGrid");if(!grid)return;$("#classSubtitle").textContent=state.students.length+" alumno"+(state.students.length===1?"":"s")+" · "+state.rubric.length+" preguntas";grid.innerHTML="";state.students.forEach(s=>{const t=totals(s),card=document.createElement("article");card.className="student-card";card.innerHTML='<div class="student-card-top"><div class="avatar">'+esc(s.name.charAt(0).toUpperCase())+'</div><button class="icon-btn delete-student" title="Eliminar">×</button></div><h3>'+esc(s.name)+'</h3><div class="student-result"><strong>'+fmt(t.pct)+'%</strong><span>'+fmt(t.got)+' / '+fmt(t.max)+' puntos</span></div><div class="mini-progress"><div style="width:'+t.progress+'%"></div></div><div class="student-card-meta">'+t.ev+' / '+t.total+' preguntas evaluadas</div><button class="primary-btn full-btn evaluate-student" data-id="'+s.id+'">Evaluar</button>';card.querySelector(".evaluate-student").onclick=()=>{state.activeStudentId=s.id;showView("rubricView");renderRubric();};card.querySelector(".delete-student").onclick=()=>deleteStudent(s.id);grid.appendChild(card)})}
function updateScore(){const s=current();if(!s)return;const t=totals(s);$("#scoreObtained").textContent=fmt(t.got);$("#scoreMax").textContent=fmt(t.max);$("#scorePercent").textContent=fmt(t.pct);$("#progressText").textContent=t.ev+" / "+t.total+" preguntas evaluadas";$("#progressPercent").textContent=Math.round(t.progress)+"%";$("#progressFill").style.width=t.progress+"%";$("#activeStudentName").textContent=s.name;const summary=$("#criterionSummary");summary.innerHTML="";groups(state.rubric).forEach((items,c)=>{const sel=getSelectionMap(s),mx=items.reduce((a,x)=>a+x.max,0),ob=items.reduce((a,x)=>a+(sel.get(x.id)?.points||0),0),pill=document.createElement("div");pill.className="criterion-pill";pill.innerHTML=esc(c)+" <strong>"+fmt(mx?ob/mx*100:0)+"%</strong>";summary.appendChild(pill)})}
function setLevel(qid,key){const s=ensureStudent(),sel=getSelectionMap(s),item=state.rubric.find(x=>x.id===qid),level=item.levels.find(x=>x.key===key);sel.set(qid,level);s.selections=[...sel];save();renderRubric()}
function renderRubric(){const s=current();if(!s)return;updateScore();if(state.view==="full")renderFull();else if(state.view==="quick")renderQuick();else renderResults()}
function renderFull(){const box=$("#rubricContainer");box.classList.remove("hidden");$("#quickContainer").classList.add("hidden");$("#resultsContainer").classList.add("hidden");$("#modeHelp").textContent="Rúbrica completa";box.innerHTML="";const sel=getSelectionMap(current());groups(state.rubric).forEach((items,c)=>{const sec=document.createElement("section");sec.className="criterion-block";const mx=items.reduce((a,x)=>a+x.max,0),ob=items.reduce((a,x)=>a+(sel.get(x.id)?.points||0),0),ev=items.filter(x=>sel.has(x.id)).length;sec.innerHTML='<div class="criterion-head"><h2 class="criterion-title">'+esc(c)+'</h2><div class="criterion-meta">'+ev+" / "+items.length+" evaluadas · "+fmt(ob)+" / "+fmt(mx)+" puntos</div></div>";items.forEach(item=>{const chosen=sel.get(item.id),card=document.createElement("article");card.className="question-card";card.innerHTML='<div class="question-top"><div><h3 class="question-title">'+esc(item.question)+'</h3><p class="question-aspect">'+esc(item.aspect)+'</p></div><div class="question-score">'+(chosen?fmt(chosen.points):"—")+" / "+fmt(item.max)+'</div></div><div class="level-grid">'+item.levels.map(l=>'<button class="level-btn '+(chosen?.key===l.key?"selected":"")+'" data-q="'+item.id+'" data-level="'+l.key+'"><span class="level-name">'+l.label+" · "+l.pct+'%</span><span class="level-points">'+fmt(l.points)+' pt</span><span class="level-desc">'+esc(l.description)+"</span></button>").join("")+"</div>";card.querySelectorAll(".level-btn").forEach(b=>b.onclick=()=>setLevel(b.dataset.q,b.dataset.level));sec.appendChild(card)});box.appendChild(sec)})}
function renderQuick(){const box=$("#quickContainer");$("#rubricContainer").classList.add("hidden");box.classList.remove("hidden");$("#resultsContainer").classList.add("hidden");$("#modeHelp").textContent="Una pregunta cada vez";const item=state.rubric[state.quickIndex]||state.rubric[0];if(!item){box.innerHTML="<div class='empty-state'>No hay preguntas.</div>";return}const s=current(),sel=getSelectionMap(s),chosen=sel.get(item.id);box.innerHTML='<div class="quick-head"><div><span class="eyebrow">PREGUNTA '+(state.quickIndex+1)+" DE "+state.rubric.length+'</span><h2>'+esc(item.question)+'</h2><p>'+esc(item.criterion)+" · "+esc(item.aspect)+'</p></div><div class="quick-score">'+(chosen?fmt(chosen.points):"—")+" / "+fmt(item.max)+"</div></div><div class="quick-levels">'+item.levels.map(l=>'<button class="quick-level '+(chosen?.key===l.key?"selected":"")+'" data-level="'+l.key+'"><span class="quick-level-top"><strong>'+l.label+"</strong><b>"+l.pct+"%</b></span><span class='quick-points'>"+fmt(l.points)+" puntos</span><span class='quick-description'>"+esc(l.description)+"</span></button>").join("")+'</div><div class="quick-nav"><button id="prevQ" class="ghost-btn">← Anterior</button><div class="quick-progress">'+(state.quickIndex+1)+" / "+state.rubric.length+'</div><button id="nextQ" class="primary-btn">Siguiente →</button></div>';box.querySelectorAll(".quick-level").forEach(b=>b.onclick=()=>{setLevel(item.id,b.dataset.level);if(state.quickIndex<state.rubric.length-1){state.quickIndex++;renderQuick()}});$("#prevQ").onclick=()=>{state.quickIndex=Math.max(0,state.quickIndex-1);renderQuick()};$("#nextQ").onclick=()=>{state.quickIndex=Math.min(state.rubric.length-1,state.quickIndex+1);renderQuick()}}
function renderResults(){const box=$("#resultsContainer");$("#rubricContainer").classList.add("hidden");$("#quickContainer").classList.add("hidden");box.classList.remove("hidden");$("#modeHelp").textContent="Resumen del alumno";const s=current(),sel=getSelectionMap(s),t=totals(s);let rows="";groups(state.rubric).forEach((items,c)=>{const mx=items.reduce((a,x)=>a+x.max,0),ob=items.reduce((a,x)=>a+(sel.get(x.id)?.points||0),0),ev=items.filter(x=>sel.has(x.id)).length;rows+='<tr><td><strong>'+esc(c)+'</strong></td><td>'+ev+" / "+items.length+'</td><td>'+fmt(ob)+" / "+fmt(mx)+'</td><td><strong>'+fmt(mx?ob/mx*100:0)+"%</strong></td></tr>"});box.innerHTML='<div class="results-grid"><div class="result-hero card"><span class="eyebrow">RESULTADO</span><strong>'+fmt(t.pct)+'%</strong><span>'+fmt(t.got)+" / "+fmt(t.max)+" puntos</span><div class='result-progress'><div style='width:"+t.pct+"%'></div></div><button id='exportStudentBtn' class='primary-btn full-btn'>Descargar CSV del alumno</button></div><div class="card results-table-wrap"><h2>Resultados por criterio</h2><table class="results-table"><thead><tr><th>Criterio</th><th>Evaluadas</th><th>Puntuación</th><th>Porcentaje</th></tr></thead><tbody>'+rows+'</tbody></table></div></div><div class="card backup-card"><h2>Gestión de datos</h2><p>Los datos están guardados en este navegador. Puedes exportar una copia completa para conservarla o trasladarla a otro dispositivo.</p><div class="button-row"><button id="exportAllBtn" class="ghost-btn">Exportar sesión JSON</button><label class="file-btn ghost-btn">Importar sesión JSON<input id="importJsonInput" type="file" accept=".json" hidden></label><button id="exportAllCsvBtn" class="ghost-btn">CSV de toda la clase</button></div></div>';$("#exportStudentBtn").onclick=()=>downloadStudentCsv(s);$("#exportAllBtn").onclick=()=>downloadAllJson();$("#exportAllCsvBtn").onclick=()=>downloadAllCsv();$("#importJsonInput").onchange=importJson}
function csvEscape(v){const s=String(v??"");return '"'+s.replaceAll('"','""')+'"'}
function download(name,text,type="text/csv;charset=utf-8"){const blob=new Blob(["\ufeff"+text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function downloadStudentCsv(s){const sel=getSelectionMap(s),rows=[["Alumno","Grupo","Actividad","Criterio","Pregunta","Nivel","Porcentaje nivel","Puntuación","Máximo"]];state.rubric.forEach(q=>{const l=sel.get(q.id);rows.push([s.name,state.session.group,state.session.activity,q.criterion,q.question,l?.label||"",l?.pct??"",l?.points??"",q.max])});download("rubrica_"+safe(s.name)+".csv",rows.map(r=>r.map(csvEscape).join(";")).join("\n"))}
function downloadAllCsv(){const rows=[["Alumno","Grupo","Actividad","Criterio","Pregunta","Nivel","Porcentaje nivel","Puntuación","Máximo"]];state.students.forEach(s=>{const sel=getSelectionMap(s);state.rubric.forEach(q=>{const l=sel.get(q.id);rows.push([s.name,state.session.group,state.session.activity,q.criterion,q.question,l?.label||"",l?.pct??"",l?.points??"",q.max])})});download("rubricas_clase.csv",rows.map(r=>r.map(csvEscape).join(";")).join("\n"))}
function downloadAllJson(){const data={version:2,exportedAt:new Date().toISOString(),csv:$("#csvInput")?.value||"",rubric:state.rubric,students:state.students,session:state.session};download("rubricas_sesion.json",JSON.stringify(data,null,2),"application/json;charset=utf-8")}
function safe(s){return norm(s).replace(/[^a-z0-9áéíóúüñ_-]+/gi,"_").slice(0,50)||"alumno"}
function importJson(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);if(!Array.isArray(d.rubric)||!Array.isArray(d.students))throw Error("Archivo no válido.");state.rubric=d.rubric;state.students=d.students;state.session=d.session||{};state.activeStudentId=state.students[0]?.id||null;$("#csvInput").value=d.csv||"";save();renderStudents();renderRubric();toast("Sesión importada correctamente")}catch(err){toast(err.message||"No se pudo importar")}};reader.readAsText(file)}
function loadRubric(){try{state.rubric=parseCsv($("#csvInput").value);state.students=[];state.activeStudentId=null;state.session={group:"",activity:""};state.quickIndex=0;save();showView("classView");$("#classNav").classList.remove("hidden");renderStudents();toast("Rúbrica cargada: "+state.rubric.length+" preguntas")}catch(e){toast(e.message||"No se ha podido leer el CSV.")}}
function setup(){document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{if(!state.rubric.length)return;showView(b.dataset.view);if(b.dataset.view==="classView")renderStudents()});$("#loadBtn").onclick=loadRubric;$("#exampleBtn").onclick=()=>{$("#csvInput").value=EXAMPLE_CSV;$("#parseStatus").textContent="Ejemplo cargado."};$("#csvInput").oninput=()=>{try{$("#parseStatus").textContent="CSV válido · "+parseCsv($("#csvInput").value).length+" preguntas detectadas"}catch{if($("#csvInput").value.trim())$("#parseStatus").textContent="Revisa el formato del CSV.";else $("#parseStatus").textContent="Esperando CSV…"}};$("#resetBtn").onclick=()=>{if(state.rubric.length&&!confirm("¿Empezar una nueva rúbrica? Se borrará la sesión guardada en este navegador."))return;localStorage.removeItem("rubricas-app-v2");location.reload()};$("#addStudentBtn").onclick=()=>{$("#studentAddBox").classList.remove("hidden");$("#newStudentName").focus()};$("#confirmStudentBtn").onclick=()=>{addStudent($("#newStudentName").value);$("#newStudentName").value="";$("#studentAddBox").classList.add("hidden")};$("#newStudentName").onkeydown=e=>{if(e.key==="Enter")$("#confirmStudentBtn").click()};$("#pasteStudentsBtn").onclick=()=>{$("#studentListInput").classList.remove("hidden");$("#studentPasteActions").classList.remove("hidden");$("#studentAddBox").classList.add("hidden")};$("#cancelStudentListBtn").onclick=()=>{$("#studentListInput").classList.add("hidden");$("#studentPasteActions").classList.add("hidden")};$("#saveStudentListBtn").onclick=()=>{norm($("#studentListInput").value).split("\n").map(norm).filter(Boolean).forEach(addStudent);$("#studentListInput").value="";$("#studentListInput").classList.add("hidden");$("#studentPasteActions").classList.add("hidden");renderStudents()};$("#fullModeBtn").onclick=()=>{state.view="full";document.querySelectorAll(".mode-btn").forEach(b=>b.classList.remove("active"));$("#fullModeBtn").classList.add("active");renderRubric()};$("#quickModeBtn").onclick=()=>{state.view="quick";state.quickIndex=0;document.querySelectorAll(".mode-btn").forEach(b=>b.classList.remove("active"));$("#quickModeBtn").classList.add("active");renderRubric()};$("#resultsBtn").onclick=()=>{state.view="results";document.querySelectorAll(".mode-btn").forEach(b=>b.classList.remove("active"));$("#resultsBtn").classList.add("active");renderRubric()};$("#groupName").oninput=()=>{state.session.group=$("#groupName").value;save()};$("#activityName").oninput=()=>{state.session.activity=$("#activityName").value;save()}}
function restore(){const raw=localStorage.getItem("rubricas-app-v2");if(!raw)return;try{const d=JSON.parse(raw);state.rubric=d.rubric||[];state.students=d.students||[];state.activeStudentId=d.activeStudentId||state.students[0]?.id||null;state.session=d.session||{group:"",activity:""};if(d.csv)$("#csvInput").value=d.csv;if(state.rubric.length){$("#classNav").classList.remove("hidden");$("#groupName").value=state.session.group||"";$("#activityName").value=state.session.activity||"";showView("classView");renderStudents()}}catch{}}
setup();restore();